
server:
  port: 8084
  
spring:
  application:
    name: user-management-service
  
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/UserManagement
    username: postgres
    password: Otsi@123
    
  jpa:
   hibernate:
    ddl-auto: update
   database-platform: org.hibernate.dialect.PostgreSQL9Dialect
   show-sql: true
   
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8762/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.int}
    hostname: localhost

  
Cognito:    
      aws: 
        accesskey: AKIAYZOXA3O4HNGVWCQL
        secret_access_key: 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 
        client_id: 1tk6nn66mll5thvmgdlnuo54fi
        userpool_id: ap-south-1_gttd6A4tT
        region: ap-south-1
        idTokenPoolUrl: https://cognito-idp.ap-south-1.amazonaws.com/ap-south-1_W7vTQcho9
        
logging:
   level:
      org:
       springframework:
                security:
                       web:
                         FilterChainProxy : debug
springdoc:
  packagesToScan: com.otsi.retail.authservice   
