
 
name: CI - CD Build
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: 'maven'
          
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4
        with:
          maven-version: 3.8.2
          
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      
      
      - name: Build with Maven
        run: mvn -B package --file pom.xml -DskipTests # change location of pom.xml file   
      
        
      - name: Persistent workflow data as artificats 
        uses: actions/upload-artifact@v2
        with: 
          name: github-actions-artifact
          path: target
          
        
      - name: Clone Repo files
        run: |
          sudo su - root << EOF  
          cd /home/ && git clone https://github.com/niranjanmaradapu/usermanagement &&  cp  -rf /home/runner/work/usermanagement/usermanagement/target usermanagement  # Replace with Repository URL where war files have to save 
          EOF
          
       
        
      - name: Commit & Push changes
        uses: Andro999b/push@v1.3
        with:
          github_token: ${{ secrets.PERSONAL_TOKEN }}
          author_email: niranjan.maradapu@otsi.co.in 
          repository: niranjanmaradapu/usermanagement
          directory: /home/usermanagement/
          
      
          
     
